version: '3.7'

services:

  hadoop:
    platform: linux/amd64
    build:
      context: ./hadoop/
    #image: sequenceiq/hadoop-docker:2.7.0
    command: "/etc/bootstrap.sh -d"
    ports:
      - "9000:9000"
      - "50070:50070"
      - "50075:50075"
    hostname: hadoop

  rclone:
    image: rclone/rclone
    entrypoint: ""
    command: '/trials/copy-check-move.sh'
    volumes:
      - "./config:/config/rclone"
      - "./trials:/trials"
